language: nix

matrix:
  fast_finish: true
  include:
    - env: GHCVER=ghcjsHEAD
    - env: GHCVER=ghcHEAD
    - env: GHCVER=ghc802
    - env: GHCVER=ghc801
    - env: GHCVER=ghc7103
    - env: GHCVER=ghc7102
    - env: GHCVER=ghc784
    - env: GHCVER=ghc783
    - env: GHCVER=ghc763
  allow_failures:
    - env: GHCVER=ghcjs
    - env: GHCVER=ghcjsHEAD
    - env: GHCVER=ghcHEAD
    - env: GHCVER=ghc7103
    - env: GHCVER=ghc7102
    - env: GHCVER=ghc784
    - env: GHCVER=ghc783
    - env: GHCVER=ghc763

before_install:
  - nix-channel --list
  - nix-channel --update

script:
  - nix-build -A hackernews --argstr compiler $GHCVER
  - ./build/phantomjs.sh
